import { useState, useEffect } from "react";
import { Card, CardContent, CardHeader, CardTitle } from "@/stackwise-demo/components/ui/card";
import { Button } from "@/stackwise-demo/components/ui/button";
import { Badge } from "@/stackwise-demo/components/ui/badge";
import { Textarea } from "@/stackwise-demo/components/ui/textarea";
import { Label } from "@/stackwise-demo/components/ui/label";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/stackwise-demo/components/ui/select";
import { ThreeColumnLayout } from "@/stackwise-demo/components/layouts/ThreeColumnLayout";
import { QuickActions } from "@/stackwise-demo/components/QuickActions";
import { 
  FileText, CheckCircle, Send, Download, Mail, Edit, TrendingUp, 
  TrendingDown, Target, Sparkles, Calendar, Users, DollarSign, BarChart3, AlertCircle
} from "lucide-react";
import { useToast } from "@/stackwise-demo/hooks/use-toast";

interface KPI {
  label: string;
  value: string;
  delta: string;
  trend: 'up' | 'down' | 'flat';
}

export default function LeadershipSalesReports() {
  const [currentStep, setCurrentStep] = useState('leadership');
  const [reportType, setReportType] = useState<'monthly' | 'quarterly'>('monthly');
  
  // Pre-populate with dummy data
  const [leadershipReport, setLeadershipReport] = useState(`**Overview**

This month, we focused on pipeline velocity and saw an 8% improvement from stronger ABM engagement. Our strategic investments in HITL AI are delivering measurable results across all key metrics.

**Performance Summary**
• MQLs: 241 (+8%)
• Opportunities: 47 / $185K (+3%)
• Pipeline Influenced: $185K (+5%)
• CPL: $62 (-4%)
• Deals Closed: 12 (+2)
• Revenue: $310K (+6%)

**Highlights & Wins**
• Campaign X drove 350 new contacts (+25% MoM)
• 3 Tier-1 accounts moved to proposal stage
• Engagement rate increased by 14%
• Mid-funnel conversion improved to 4.2%

**Optimization Tracker**
• Landing page A/B variant improved CPL by 18%
• Workflow automation improved follow-up times by 22%
• ABM playbook conversion rate reached 22%

**Next Focus & Strategic Priorities**
• Launch refreshed ABM tier strategy for Q1
• Align campaign handoff process with sales team
• Update analytics tagging for improved ROI tracking
• Scale successful ABM playbooks to additional Tier 1 accounts

**Recommendations**
1. Increase content production to 15/week with focus on interactive formats
2. Launch targeted mid-market positioning campaign (identified gap opportunity)
3. Scale successful ABM playbooks to additional Tier 1 accounts

Overall, our data-driven approach and strategic investments in HITL AI are delivering measurable results. Leadership support for recommended initiatives will help maintain this positive trajectory.`);
  
  const [salesReport, setSalesReport] = useState(`**Snapshot**

This week, lead-to-SQL conversion improved as ABM signals drove stronger engagement (+6% WoW). Pipeline velocity continues to accelerate across all stages.

**Performance Pulse**
• MQLs Added: 68 (+12% WoW)
• New Opportunities: $74K (+6% WoW)
• Pipeline Influenced: $210K (+8% WoW)
• Deals Closed: $92K (+4% WoW)
• CPL: $59 (-3% WoW)
• Conversion Rate: 4.2% (+0.3pp)

**Highlights & Wins**
• 4 new accounts added from ABM Tier 2 list
• 2 large deals advanced to negotiation stage ($45K total value)
• Pipeline velocity increased 6% WoW
• Email engagement rate up 18% from personalization improvements

**In-Flight Optimizations**
• Refined lead routing by region for faster follow-up
• Improved nurture timing based on engagement signals
• Enhanced qualification criteria reducing false positives by 12%

**Account Movement**
• Acme Corp → Demo Scheduled ($28K opportunity)
• TechStart Inc → Proposal Sent ($17K opportunity)
• GlobalCo → Negotiation ($45K opportunity)

**Next Week Priorities**
• Follow up on 3 pending proposals
• Launch new nurture sequence for mid-funnel leads
• Conduct win/loss analysis on Q4 closed deals
• Refine ICP targeting based on recent conversions

Keep up the momentum. The pipeline is healthy and conversion trends are strong.`);
  
  const [autoGenerated, setAutoGenerated] = useState(true);
  const [assignedReviewer, setAssignedReviewer] = useState('sarah.johnson@stackwise.com');
  const [isEditMode, setIsEditMode] = useState(false);
  const [leadershipApproved, setLeadershipApproved] = useState(false);
  const [salesApproved, setSalesApproved] = useState(false);
  const { toast } = useToast();

  const moduleColor = '#6218df';

  const kpis: KPI[] = [
    { label: 'MQLs', value: '241', delta: '+8%', trend: 'up' },
    { label: 'Opportunities', value: '47 / $185K', delta: '+3%', trend: 'up' },
    { label: 'Pipeline Influenced', value: '$185K', delta: '+5%', trend: 'up' },
    { label: 'CPL', value: '$62', delta: '-4%', trend: 'down' },
    { label: 'Deals Closed', value: '12', delta: '+2', trend: 'up' },
    { label: 'Revenue', value: '$310K', delta: '+6%', trend: 'up' },
  ];

  const salesKPIs: KPI[] = [
    { label: 'MQLs Added', value: '68', delta: '+12% WoW', trend: 'up' },
    { label: 'New Opportunities', value: '$74K', delta: '+6% WoW', trend: 'up' },
    { label: 'Pipeline Influenced', value: '$210K', delta: '+8% WoW', trend: 'up' },
    { label: 'Deals Closed', value: '$92K', delta: '+4% WoW', trend: 'up' },
    { label: 'CPL', value: '$59', delta: '-3% WoW', trend: 'down' },
    { label: 'Conversion Rate', value: '4.2%', delta: '+0.3pp', trend: 'up' },
  ];

  const compileLeadership = (period: 'monthly' | 'quarterly') => {
    const periodLabel = period === 'monthly' ? 'month' : 'quarter';
    return `**Overview**

This ${periodLabel}, we focused on pipeline velocity and saw an 8% improvement from stronger ABM engagement. Our strategic investments in HITL AI are delivering measurable results across all key metrics.

**Performance Summary**
${kpis.map(k => `• ${k.label}: ${k.value} (${k.delta})`).join('\n')}

**Highlights & Wins**
• Campaign X drove 350 new contacts (+25% MoM)
• 3 Tier-1 accounts moved to proposal stage
• Engagement rate increased by 14%
• Mid-funnel conversion improved to 4.2%

**Optimization Tracker**
• Landing page A/B variant improved CPL by 18%
• Workflow automation improved follow-up times by 22%
• ABM playbook conversion rate reached 22%

**Next Focus & Strategic Priorities**
• Launch refreshed ABM tier strategy for Q1
• Align campaign handoff process with sales team
• Update analytics tagging for improved ROI tracking
• Scale successful ABM playbooks to additional Tier 1 accounts

**Recommendations**
1. Increase content production to 15/week with focus on interactive formats
2. Launch targeted mid-market positioning campaign (identified gap opportunity)
3. Scale successful ABM playbooks to additional Tier 1 accounts

Overall, our data-driven approach and strategic investments in HITL AI are delivering measurable results. Leadership support for recommended initiatives will help maintain this positive trajectory.`;
  };

  const compileSales = () => {
    return `**Snapshot**

This week, lead-to-SQL conversion improved as ABM signals drove stronger engagement (+6% WoW). Pipeline velocity continues to accelerate across all stages.

**Performance Pulse**
${salesKPIs.map(k => `• ${k.label}: ${k.value} (${k.delta})`).join('\n')}

**Highlights & Wins**
• 4 new accounts added from ABM Tier 2 list
• 2 large deals advanced to negotiation stage ($45K total value)
• Pipeline velocity increased 6% WoW
• Email engagement rate up 18% from personalization improvements

**In-Flight Optimizations**
• Refined lead routing by region for faster follow-up
• Improved nurture timing based on engagement signals
• Enhanced qualification criteria reducing false positives by 12%

**Account Movement**
• Acme Corp → Demo Scheduled ($28K opportunity)
• TechStart Inc → Proposal Sent ($17K opportunity)
• GlobalCo → Negotiation ($45K opportunity)

**Next Week Priorities**
• Follow up on 3 pending proposals
• Launch new nurture sequence for mid-funnel leads
• Conduct win/loss analysis on Q4 closed deals
• Refine ICP targeting based on recent conversions

Keep up the momentum. The pipeline is healthy and conversion trends are strong.`;
  };

  const autoGenerateLeadership = () => {
    setLeadershipReport(compileLeadership(reportType));
    setAutoGenerated(true);
    toast({
      title: "Leadership Report Generated",
      description: `AI has generated your ${reportType} leadership report.`
    });
  };

  const autoGenerateSales = () => {
    setSalesReport(compileSales());
    setAutoGenerated(true);
    toast({
      title: "Sales Report Generated",
      description: "AI has generated your weekly sales report."
    });
  };


  const steps = [
    { id: 'leadership', label: 'Leadership Report', description: 'Monthly/Quarterly summary' },
    { id: 'sales', label: 'Sales Report', description: 'Weekly performance snapshot' },
    { id: 'review', label: 'Review & Edit', description: 'HITL refinement' },
    { id: 'finalize', label: 'Finalize', description: 'Approve for distribution' },
    { id: 'send', label: 'Send/Export', description: 'Distribute reports' }
  ];

  const renderLeadership = () => (
    <div className="space-y-6">
      <div className="flex items-center justify-between">
        <div>
          <h3 className="text-lg font-semibold">Leadership Report</h3>
          <p className="text-sm text-muted-foreground">Select period and generate AI-powered summary</p>
        </div>
        <div className="flex items-center gap-3">
          <Label className="text-sm">Period:</Label>
          <Select value={reportType} onValueChange={(v: 'monthly' | 'quarterly') => setReportType(v)}>
            <SelectTrigger className="w-32" data-testid="select-period">
              <SelectValue />
            </SelectTrigger>
            <SelectContent>
              <SelectItem value="monthly">Monthly</SelectItem>
              <SelectItem value="quarterly">Quarterly</SelectItem>
            </SelectContent>
          </Select>
          <Button onClick={autoGenerateLeadership} data-testid="button-generate-leadership">
            <Sparkles className="w-4 h-4 mr-2" />
            Generate Now
          </Button>
        </div>
      </div>

      {/* KPI Summary */}
      <Card className="border-2 border-purple-200">
        <CardHeader>
          <CardTitle className="flex items-center gap-2" style={{ color: moduleColor }}>
            <BarChart3 className="w-5 h-5" />
            Key Performance Indicators
          </CardTitle>
        </CardHeader>
        <CardContent>
          <div className="grid grid-cols-2 md:grid-cols-3 gap-4">
            {kpis.map((kpi, i) => (
              <div key={i} className="bg-purple-50 p-4 rounded-lg border border-purple-100">
                <div className="flex justify-between items-start mb-2">
                  <p className="text-sm font-semibold text-gray-700">{kpi.label}</p>
                  <div className="flex items-center gap-1">
                    {kpi.trend === 'up' && <TrendingUp className="w-4 h-4 text-green-600" />}
                    {kpi.trend === 'down' && <TrendingDown className="w-4 h-4 text-red-600" />}
                    <span className={`text-xs font-semibold ${kpi.trend === 'up' ? 'text-green-600' : kpi.trend === 'down' ? 'text-red-600' : 'text-gray-600'}`}>
                      {kpi.delta}
                    </span>
                  </div>
                </div>
                <p className="text-xl font-bold" style={{ color: moduleColor }}>{kpi.value}</p>
              </div>
            ))}
          </div>
        </CardContent>
      </Card>

      {/* Auto-generated Report Preview */}
      {leadershipReport && (
        <Card className="border-2 border-purple-200">
          <CardHeader>
            <div className="flex items-center justify-between">
              <CardTitle className="flex items-center gap-2" style={{ color: moduleColor }}>
                <FileText className="w-5 h-5" />
                AI-Generated Report Preview
              </CardTitle>
              <Badge className="bg-purple-100 text-purple-700">Auto-Generated</Badge>
            </div>
          </CardHeader>
          <CardContent>
            <div className="prose prose-sm max-w-none">
              <pre className="whitespace-pre-wrap font-sans text-sm text-gray-700 bg-gray-50 p-4 rounded-lg">
                {leadershipReport}
              </pre>
            </div>
            <div className="flex gap-2 mt-4">
              <Button onClick={() => setCurrentStep('review')} data-testid="button-continue-to-review">
                Continue to Review
              </Button>
              <Button variant="outline" onClick={autoGenerateLeadership} data-testid="button-regenerate-leadership">
                Regenerate
              </Button>
            </div>
          </CardContent>
        </Card>
      )}

      {!leadershipReport && (
        <Card className="border border-dashed border-gray-300 bg-gray-50">
          <CardContent className="p-8 text-center">
            <Sparkles className="w-12 h-12 mx-auto mb-3 text-gray-400" />
            <p className="text-gray-600 mb-2">No report generated yet</p>
            <p className="text-sm text-gray-500">Click "Generate Now" to create an AI-powered {reportType} leadership report</p>
          </CardContent>
        </Card>
      )}
    </div>
  );

  const renderSales = () => (
    <div className="space-y-6">
      <div className="flex items-center justify-between">
        <div>
          <h3 className="text-lg font-semibold">Weekly Sales Performance</h3>
          <p className="text-sm text-muted-foreground">Auto-generated snapshot for sales team</p>
        </div>
        <Button onClick={autoGenerateSales} data-testid="button-generate-sales">
          <Sparkles className="w-4 h-4 mr-2" />
          Generate Now
        </Button>
      </div>

      {/* Sales KPIs */}
      <Card className="border-2 border-purple-200">
        <CardHeader>
          <CardTitle className="flex items-center gap-2" style={{ color: moduleColor }}>
            <DollarSign className="w-5 h-5" />
            Weekly Performance Metrics
          </CardTitle>
        </CardHeader>
        <CardContent>
          <div className="grid grid-cols-2 md:grid-cols-3 gap-4">
            {salesKPIs.map((kpi, i) => (
              <div key={i} className="bg-purple-50 p-4 rounded-lg border border-purple-100">
                <div className="flex justify-between items-start mb-2">
                  <p className="text-sm font-semibold text-gray-700">{kpi.label}</p>
                  <div className="flex items-center gap-1">
                    {kpi.trend === 'up' && <TrendingUp className="w-4 h-4 text-green-600" />}
                    {kpi.trend === 'down' && <TrendingDown className="w-4 h-4 text-red-600" />}
                    <span className={`text-xs font-semibold ${kpi.trend === 'up' ? 'text-green-600' : kpi.trend === 'down' ? 'text-red-600' : 'text-gray-600'}`}>
                      {kpi.delta}
                    </span>
                  </div>
                </div>
                <p className="text-xl font-bold" style={{ color: moduleColor }}>{kpi.value}</p>
              </div>
            ))}
          </div>
        </CardContent>
      </Card>

      {/* Auto-generated Sales Report */}
      {salesReport && (
        <Card className="border-2 border-purple-200">
          <CardHeader>
            <div className="flex items-center justify-between">
              <CardTitle className="flex items-center gap-2" style={{ color: moduleColor }}>
                <FileText className="w-5 h-5" />
                AI-Generated Sales Report
              </CardTitle>
              <Badge className="bg-purple-100 text-purple-700">Auto-Generated</Badge>
            </div>
          </CardHeader>
          <CardContent>
            <div className="prose prose-sm max-w-none">
              <pre className="whitespace-pre-wrap font-sans text-sm text-gray-700 bg-gray-50 p-4 rounded-lg">
                {salesReport}
              </pre>
            </div>
            <div className="flex gap-2 mt-4">
              <Button onClick={() => setCurrentStep('review')} data-testid="button-sales-to-review">
                Continue to Review
              </Button>
              <Button variant="outline" onClick={autoGenerateSales} data-testid="button-regenerate-sales">
                Regenerate
              </Button>
            </div>
          </CardContent>
        </Card>
      )}

      {!salesReport && (
        <Card className="border border-dashed border-gray-300 bg-gray-50">
          <CardContent className="p-8 text-center">
            <Sparkles className="w-12 h-12 mx-auto mb-3 text-gray-400" />
            <p className="text-gray-600 mb-2">No report generated yet</p>
            <p className="text-sm text-gray-500">Click "Generate Now" to create an AI-powered weekly sales report</p>
          </CardContent>
        </Card>
      )}
    </div>
  );

  const renderReview = () => (
    <div className="space-y-6">
      <div className="flex items-center justify-between">
        <div>
          <h3 className="text-lg font-semibold">Review & Edit (HITL)</h3>
          <p className="text-sm text-muted-foreground">Human-in-the-loop: Review and refine AI-generated reports</p>
        </div>
        <div className="flex items-center gap-2">
          <Badge className="text-xs bg-purple-100 text-purple-700">HITL Workflow</Badge>
          <Button
            variant={isEditMode ? "default" : "outline"}
            size="sm"
            onClick={() => setIsEditMode(!isEditMode)}
            data-testid="button-toggle-edit"
          >
            <Edit className="w-3 h-3 mr-1" />
            {isEditMode ? 'Exit Edit Mode' : 'Enter Edit Mode'}
          </Button>
        </div>
      </div>

      <Card className="border-2 border-blue-200 bg-blue-50">
        <CardHeader>
          <CardTitle className="text-sm flex items-center gap-2 text-blue-700">
            <Target className="w-4 h-4" />
            HITL Process: Your Role
          </CardTitle>
        </CardHeader>
        <CardContent>
          <p className="text-sm text-gray-700">
            The AI has generated comprehensive reports based on your metrics. Your role is to:
            (1) Review narratives for accuracy and tone, (2) Edit or enhance sections needing refinement,
            (3) Approve reports for distribution. This human oversight ensures quality and strategic alignment.
          </p>
        </CardContent>
      </Card>

      {/* Leadership Report Review */}
      {leadershipReport && (
        <Card className="border-2 border-purple-200">
          <CardHeader>
            <div className="flex items-center justify-between">
              <CardTitle className="flex items-center gap-2" style={{ color: moduleColor }}>
                <Users className="w-5 h-5" />
                Leadership Report ({reportType})
              </CardTitle>
              <Badge variant="secondary">Reviewer: {assignedReviewer}</Badge>
            </div>
          </CardHeader>
          <CardContent>
            {isEditMode ? (
              <Textarea
                value={leadershipReport}
                onChange={(e) => setLeadershipReport(e.target.value)}
                className="min-h-96 font-mono text-sm"
                data-testid="textarea-leadership"
              />
            ) : (
              <div className="prose prose-sm max-w-none">
                <pre className="whitespace-pre-wrap font-sans text-sm text-gray-700 bg-gray-50 p-4 rounded-lg">
                  {leadershipReport}
                </pre>
              </div>
            )}
          </CardContent>
        </Card>
      )}

      {/* Sales Report Review */}
      {salesReport && (
        <Card className="border-2 border-purple-200">
          <CardHeader>
            <div className="flex items-center justify-between">
              <CardTitle className="flex items-center gap-2" style={{ color: moduleColor }}>
                <DollarSign className="w-5 h-5" />
                Sales Report (Weekly)
              </CardTitle>
              <Badge variant="secondary">Reviewer: {assignedReviewer}</Badge>
            </div>
          </CardHeader>
          <CardContent>
            {isEditMode ? (
              <Textarea
                value={salesReport}
                onChange={(e) => setSalesReport(e.target.value)}
                className="min-h-96 font-mono text-sm"
                data-testid="textarea-sales"
              />
            ) : (
              <div className="prose prose-sm max-w-none">
                <pre className="whitespace-pre-wrap font-sans text-sm text-gray-700 bg-gray-50 p-4 rounded-lg">
                  {salesReport}
                </pre>
              </div>
            )}
          </CardContent>
        </Card>
      )}

      {!leadershipReport && !salesReport && (
        <Card className="border border-dashed border-gray-300 bg-gray-50">
          <CardContent className="p-8 text-center">
            <AlertCircle className="w-12 h-12 mx-auto mb-3 text-gray-400" />
            <p className="text-gray-600 mb-2">No reports available for review</p>
            <p className="text-sm text-gray-500">Generate reports in the Leadership or Sales steps first</p>
          </CardContent>
        </Card>
      )}

      <div className="flex gap-2">
        <Button 
          onClick={() => setCurrentStep('finalize')} 
          disabled={!leadershipReport && !salesReport}
          data-testid="button-continue-finalize"
        >
          Continue to Finalize
        </Button>
        <Button variant="outline" onClick={() => setCurrentStep('leadership')} data-testid="button-back-leadership">
          Back to Leadership
        </Button>
      </div>
    </div>
  );

  const renderFinalize = () => (
    <div className="space-y-6">
      <div>
        <h3 className="text-lg font-semibold">Finalize Reports</h3>
        <p className="text-sm text-muted-foreground">Review and approve reports for distribution</p>
      </div>

      <Card className="border-2 border-green-200 bg-green-50">
        <CardContent className="pt-6">
          <div className="flex items-center gap-3">
            <CheckCircle className="w-8 h-8 text-green-600" />
            <div>
              <p className="font-semibold text-green-800">Reports Ready for Approval</p>
              <p className="text-sm text-green-700">All reports have been reviewed and are ready for distribution</p>
            </div>
          </div>
        </CardContent>
      </Card>

      {/* Report Summary */}
      <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
        {leadershipReport && (
          <Card className="border border-gray-200">
            <CardHeader>
              <CardTitle className="text-sm flex items-center justify-between">
                <div className="flex items-center gap-2">
                  <Users className="w-4 h-4" />
                  Leadership Report
                </div>
                <Badge variant="outline">{reportType}</Badge>
              </CardTitle>
            </CardHeader>
            <CardContent>
              <div className="space-y-2 text-sm">
                <div className="flex justify-between">
                  <span className="text-gray-600">Period:</span>
                  <span className="font-semibold">{reportType === 'monthly' ? 'Monthly' : 'Quarterly'}</span>
                </div>
                <div className="flex justify-between">
                  <span className="text-gray-600">Generated:</span>
                  <span className="font-semibold">{new Date().toLocaleDateString()}</span>
                </div>
                <div className="flex justify-between">
                  <span className="text-gray-600">Reviewer:</span>
                  <span className="font-semibold">{assignedReviewer}</span>
                </div>
                <div className="flex justify-between">
                  <span className="text-gray-600">Status:</span>
                  <Badge variant="secondary" className="text-xs">Ready</Badge>
                </div>
              </div>
              <Button 
                variant={leadershipApproved ? "default" : "outline"}
                size="sm" 
                className="w-full mt-3"
                style={leadershipApproved ? { backgroundColor: moduleColor } : {}}
                onClick={() => {
                  setLeadershipApproved(true);
                  toast({ title: "Leadership Report Approved", description: "Report marked as approved for distribution" });
                }}
                data-testid="button-approve-leadership"
                disabled={leadershipApproved}
              >
                <CheckCircle className="w-3 h-3 mr-1" />
                {leadershipApproved ? 'Approved ✓' : 'Approve Report'}
              </Button>
            </CardContent>
          </Card>
        )}

        {salesReport && (
          <Card className="border border-gray-200">
            <CardHeader>
              <CardTitle className="text-sm flex items-center justify-between">
                <div className="flex items-center gap-2">
                  <DollarSign className="w-4 h-4" />
                  Sales Report
                </div>
                <Badge variant="outline">Weekly</Badge>
              </CardTitle>
            </CardHeader>
            <CardContent>
              <div className="space-y-2 text-sm">
                <div className="flex justify-between">
                  <span className="text-gray-600">Period:</span>
                  <span className="font-semibold">Weekly</span>
                </div>
                <div className="flex justify-between">
                  <span className="text-gray-600">Generated:</span>
                  <span className="font-semibold">{new Date().toLocaleDateString()}</span>
                </div>
                <div className="flex justify-between">
                  <span className="text-gray-600">Reviewer:</span>
                  <span className="font-semibold">{assignedReviewer}</span>
                </div>
                <div className="flex justify-between">
                  <span className="text-gray-600">Status:</span>
                  <Badge variant="secondary" className="text-xs">Ready</Badge>
                </div>
              </div>
              <Button 
                variant={salesApproved ? "default" : "outline"}
                size="sm" 
                className="w-full mt-3"
                style={salesApproved ? { backgroundColor: moduleColor } : {}}
                onClick={() => {
                  setSalesApproved(true);
                  toast({ title: "Sales Report Approved", description: "Report marked as approved for distribution" });
                }}
                data-testid="button-approve-sales"
                disabled={salesApproved}
              >
                <CheckCircle className="w-3 h-3 mr-1" />
                {salesApproved ? 'Approved ✓' : 'Approve Report'}
              </Button>
            </CardContent>
          </Card>
        )}
      </div>

      <div className="flex gap-2">
        <Button onClick={() => setCurrentStep('send')} data-testid="button-continue-send">
          Continue to Send/Export
        </Button>
        <Button variant="outline" onClick={() => setCurrentStep('review')} data-testid="button-back-review">
          Back to Review
        </Button>
      </div>
    </div>
  );

  const renderSend = () => (
    <div className="space-y-6">
      <div>
        <h3 className="text-lg font-semibold">Send & Export Reports</h3>
        <p className="text-sm text-muted-foreground">Distribute approved reports to stakeholders</p>
      </div>

      <Card className="border-2 border-green-200 bg-green-50">
        <CardContent className="pt-6">
          <div className="flex items-center gap-3">
            <CheckCircle className="w-8 h-8 text-green-600" />
            <div>
              <p className="font-semibold text-green-800">Reports Approved</p>
              <p className="text-sm text-green-700">Your reports are ready for distribution</p>
            </div>
          </div>
        </CardContent>
      </Card>

      {/* Distribution Options */}
      <Card className="border border-gray-200">
        <CardHeader>
          <CardTitle className="text-lg">Distribution Options</CardTitle>
          <p className="text-sm text-muted-foreground">Choose how to share your reports</p>
        </CardHeader>
        <CardContent className="space-y-3">
          <Card className="border border-gray-200 hover:shadow-md transition-all cursor-pointer" data-testid="option-email">
            <CardContent className="pt-4">
              <div className="flex items-center gap-3">
                <div className="p-3 rounded-lg bg-blue-50">
                  <Mail className="w-5 h-5 text-blue-600" />
                </div>
                <div className="flex-1">
                  <p className="font-semibold">Send via Email</p>
                  <p className="text-sm text-gray-600">Deliver reports directly to stakeholder inboxes</p>
                </div>
                <Button 
                  size="sm" 
                  data-testid="button-send-email"
                  onClick={() => {
                    toast({ 
                      title: "Email Sent", 
                      description: `Reports sent to ${assignedReviewer} and 12 stakeholders` 
                    });
                  }}
                >
                  Send Email
                </Button>
              </div>
            </CardContent>
          </Card>

          <Card className="border border-gray-200 hover:shadow-md transition-all cursor-pointer" data-testid="option-download">
            <CardContent className="pt-4">
              <div className="flex items-center gap-3">
                <div className="p-3 rounded-lg bg-purple-50">
                  <Download className="w-5 h-5 text-purple-600" />
                </div>
                <div className="flex-1">
                  <p className="font-semibold">Download PDF</p>
                  <p className="text-sm text-gray-600">Export as formatted PDF for offline sharing</p>
                </div>
                <Button 
                  size="sm" 
                  data-testid="button-download-pdf"
                  onClick={() => {
                    toast({ 
                      title: "Download Started", 
                      description: "Reports exported as PDF and downloading..." 
                    });
                  }}
                >
                  Download
                </Button>
              </div>
            </CardContent>
          </Card>

          <Card className="border border-gray-200 hover:shadow-md transition-all cursor-pointer" data-testid="option-schedule">
            <CardContent className="pt-4">
              <div className="flex items-center gap-3">
                <div className="p-3 rounded-lg bg-green-50">
                  <Calendar className="w-5 h-5 text-green-600" />
                </div>
                <div className="flex-1">
                  <p className="font-semibold">Schedule Recurring</p>
                  <p className="text-sm text-gray-600">Automate weekly or monthly report delivery</p>
                </div>
                <Button 
                  size="sm" 
                  data-testid="button-schedule-recurring"
                  onClick={() => {
                    toast({ 
                      title: "Recurring Report Scheduled", 
                      description: "Reports will be automatically sent every Monday at 9 AM" 
                    });
                  }}
                >
                  Schedule
                </Button>
              </div>
            </CardContent>
          </Card>
        </CardContent>
      </Card>

      {/* Report History */}
      <Card className="border border-gray-200">
        <CardHeader>
          <CardTitle className="text-lg">Report History</CardTitle>
          <p className="text-sm text-muted-foreground">Previously generated and sent reports</p>
        </CardHeader>
        <CardContent>
          <div className="space-y-2">
            {[
              { date: 'Nov 1, 2025', title: 'Q4 Executive Summary', type: 'Leadership', status: 'Sent to 12 recipients' },
              { date: 'Oct 28, 2025', title: 'Weekly Sales Performance', type: 'Sales', status: 'Sent to 8 recipients' },
              { date: 'Oct 21, 2025', title: 'Weekly Sales Performance', type: 'Sales', status: 'Sent to 8 recipients' },
              { date: 'Oct 1, 2025', title: 'Monthly Leadership Report', type: 'Leadership', status: 'Sent to 15 recipients' }
            ].map((report, idx) => (
              <div key={idx} className="flex items-center justify-between p-3 border border-gray-200 rounded-md hover:bg-gray-50" data-testid={`report-history-${idx}`}>
                <div className="flex items-center gap-3">
                  {report.type === 'Leadership' ? (
                    <Users className="w-4 h-4 text-purple-600" />
                  ) : (
                    <DollarSign className="w-4 h-4 text-green-600" />
                  )}
                  <div>
                    <p className="font-semibold text-sm">{report.title}</p>
                    <p className="text-xs text-gray-600">{report.date} • {report.status}</p>
                  </div>
                </div>
                <div className="flex gap-2">
                  <Badge variant="outline" className="text-xs">{report.type}</Badge>
                  <Button size="sm" variant="outline" data-testid={`button-view-${idx}`}>View</Button>
                </div>
              </div>
            ))}
          </div>
        </CardContent>
      </Card>

      <div className="flex gap-2">
        <Button onClick={() => {
          setCurrentStep('leadership');
          setLeadershipReport('');
          setSalesReport('');
        }} data-testid="button-create-new">
          Create New Report
        </Button>
        <Button variant="outline" onClick={() => setCurrentStep('finalize')} data-testid="button-back-finalize">
          Back to Finalize
        </Button>
      </div>
    </div>
  );

  const renderContent = () => (
    <div className="h-full overflow-y-auto bg-white">
      <div className="bg-white px-8 py-4 border-b border-purple-100 sticky top-0 z-10">
        <h1 className="text-3xl font-bold mb-2" style={{ color: moduleColor }}>
          Leadership & Sales Reports
        </h1>
        <p className="text-gray-600 max-w-3xl">
          AI-powered report generation with Human-in-the-Loop review and approval workflow.
        </p>
      </div>

      <div className="p-4 sm:p-6 lg:p-8">
        {currentStep === 'leadership' && renderLeadership()}
        {currentStep === 'sales' && renderSales()}
        {currentStep === 'review' && renderReview()}
        {currentStep === 'finalize' && renderFinalize()}
        {currentStep === 'send' && renderSend()}
      </div>
    </div>
  );

  return (
    <ThreeColumnLayout
      leftNav={null}
      steps={steps}
      currentStep={currentStep}
      onStepChange={setCurrentStep}
      content={
        <div className="h-full overflow-y-auto">
          <div className="sticky top-0 z-10 bg-white dark:bg-background pb-4 border-b px-8 pt-4">
            <QuickActions module="PulseHub" />
          </div>
          {renderContent()}
        </div>
      }
      moduleColor={moduleColor}
      completedSteps={[]}
      featureName="Leadership & Sales Reports"
    />
  );
}
